# 01. Pytorch Word Embedding
- Pretrained Embedding 활용

##### 0) 라이브러리 불러오기

In [17]:
# (1) 자연어처리 라이브러리
import gensim

# (2) 딥러닝 라이브러리
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# (3) 기타 라이브러리
import numpy as np

In [18]:
torch.manual_seed(1)

##### 1) Pytorch Word Embedding 흐름

(1) Word2Idx 정의 !

In [19]:
word_to_idx = {"hello": 0, "world": 1}

(2) 모델(Word_Embedding_Matrix) 정의

In [20]:
embedding = nn.Embedding(2, 5)

embedding

(3) LookUp Tensor 추출 !!

In [22]:
lookup_tensor = torch.tensor([word_to_idx["hello"]], dtype=torch.long)

lookup_tensor

(4) 모델(Word_Embedding_Matrix) 결과 출력

In [24]:
embedding(lookup_tensor)

tensor([[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519]],
       grad_fn=<EmbeddingBackward0>)


##### 3) Pretrained 모델(Word Embedding Matrix) 불러오기

In [25]:
word2vec_model = gensim.models.KeyedVectors.load_word2vec_format('./word2vec_ko_50.model') # !
Word_Embedding_Matrix = torch.FloatTensor(word2vec_model.vectors) # weights !!

- word2vec_model

In [26]:
type(word2vec_model)

gensim.models.keyedvectors.KeyedVectors

In [27]:
word2vec_model

In [28]:
word2vec_model.vectors

array([[-0.24869117,  0.36853087,  0.08808379, ...,  0.17455211,
         0.53181475,  0.24320409],
       [-0.3202381 ,  0.17195675, -0.2593631 , ..., -0.56549656,
         0.22660756,  0.22523348],
       [-0.08106741,  0.27330452,  0.10495282, ..., -0.48966533,
         0.13854298, -0.18827364],
       ...,
       [ 0.10107071,  0.13921157, -0.05491875, ..., -0.30770868,
         0.1990372 ,  0.01810699],
       [ 0.11634092,  0.0810578 , -0.08624679, ..., -0.27115765,
         0.19006865,  0.05816119],
       [ 0.03469321,  0.06472182, -0.11103159, ..., -0.19412237,
         0.15011725,  0.1316599 ]], dtype=float32)

In [29]:
word2vec_model["최민식"] # !!

array([ 0.16608578,  0.1375947 ,  0.271771  , -0.2588549 , -0.19173276,
       -0.16698623,  0.07860588,  0.8292565 , -0.3245534 , -0.38270855,
       -0.00501213,  0.05694433, -0.34075397,  0.5075239 ,  0.22071695,
       -0.3237845 ,  0.0941361 ,  0.19125557, -0.40648293, -0.31980386,
       -0.3000595 ,  0.09706737,  0.5012349 ,  0.21016343,  0.07618044,
       -0.11245659, -0.48303747,  0.32796028, -0.27070236,  0.51093596,
       -0.12364557, -0.30212128, -0.18666123,  0.03466694, -0.10568103,
       -0.18983434,  0.6698006 ,  0.11746198,  0.10840736, -0.35072044,
        0.53534514, -0.14359848,  0.04691505,  0.21365473,  0.27082622,
       -0.17516938,  0.21892266, -0.39058322,  0.06152136,  0.18474238],
      dtype=float32)

In [30]:
word2vec_model.key_to_index["최민식"] # !!

3374

In [31]:
print(word2vec_model.index_to_key[3374]) # !!

최민식


- Word_Embedding_Matrix

In [32]:
type(Word_Embedding_Matrix)

torch.Tensor

In [33]:
Word_Embedding_Matrix

tensor([[-0.2487,  0.3685,  0.0881,  ...,  0.1746,  0.5318,  0.2432],
        [-0.3202,  0.1720, -0.2594,  ..., -0.5655,  0.2266,  0.2252],
        [-0.0811,  0.2733,  0.1050,  ..., -0.4897,  0.1385, -0.1883],
        ...,
        [ 0.1011,  0.1392, -0.0549,  ..., -0.3077,  0.1990,  0.0181],
        [ 0.1163,  0.0811, -0.0862,  ..., -0.2712,  0.1901,  0.0582],
        [ 0.0347,  0.0647, -0.1110,  ..., -0.1941,  0.1501,  0.1317]])

In [34]:
len(Word_Embedding_Matrix)

16477

In [35]:
Word_Embedding_Matrix.shape

torch.Size([16477, 50])

In [36]:
Word_Embedding_Matrix[[3374]]

tensor([[ 0.1661,  0.1376,  0.2718, -0.2589, -0.1917, -0.1670,  0.0786,  0.8293,
         -0.3246, -0.3827, -0.0050,  0.0569, -0.3408,  0.5075,  0.2207, -0.3238,
          0.0941,  0.1913, -0.4065, -0.3198, -0.3001,  0.0971,  0.5012,  0.2102,
          0.0762, -0.1125, -0.4830,  0.3280, -0.2707,  0.5109, -0.1236, -0.3021,
         -0.1867,  0.0347, -0.1057, -0.1898,  0.6698,  0.1175,  0.1084, -0.3507,
          0.5353, -0.1436,  0.0469,  0.2137,  0.2708, -0.1752,  0.2189, -0.3906,
          0.0615,  0.1847]])

- word2vec_model -> Word_Embedding_Matrix

In [37]:
Word_Embedding_Matrix[word2vec_model.key_to_index["최민식"]] # !!

tensor([ 0.1661,  0.1376,  0.2718, -0.2589, -0.1917, -0.1670,  0.0786,  0.8293,
        -0.3246, -0.3827, -0.0050,  0.0569, -0.3408,  0.5075,  0.2207, -0.3238,
         0.0941,  0.1913, -0.4065, -0.3198, -0.3001,  0.0971,  0.5012,  0.2102,
         0.0762, -0.1125, -0.4830,  0.3280, -0.2707,  0.5109, -0.1236, -0.3021,
        -0.1867,  0.0347, -0.1057, -0.1898,  0.6698,  0.1175,  0.1084, -0.3507,
         0.5353, -0.1436,  0.0469,  0.2137,  0.2708, -0.1752,  0.2189, -0.3906,
         0.0615,  0.1847])

In [38]:
Word_Embedding_Matrix[word2vec_model.key_to_index["제로투"]]

KeyError: '제로투'

In [ ]:
Word_Embedding_Matrix[word2vec_model.key_to_index["<unk>"]] # !!

KeyError: ignored

##### 4) Pretrained 모델(Word Embedding Matrix) 불러오기 + Unkown Word2Vec 추가

In [39]:
word2vec_model.add_vector("<unk>", np.zeros(50)) # !!

Word_Embedding_Matrix = torch.FloatTensor(word2vec_model.vectors)

c:\Users\Bang\Anaconda\envs\BangEnv\lib\site-packages\gensim\models\keyedvectors.py:478: UserWarning: Adding single vectors to a KeyedVectors which grows by one each time can be costly. Consider adding in batches or preallocating to the required size.
  warnings.warn(


- Word2Vec_model

In [40]:
len(word2vec_model)

16478

In [41]:
word2vec_model.index_to_key[16477]

'<unk>'

In [42]:
word2vec_model[16477] # !!

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

- Word_Embedding_Matrix

In [43]:
Word_Embedding_Matrix[16477] # !!

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

##### 5) 모델(Word_Embedding_Matrix) 정의

In [44]:
embedding = nn.Embedding.from_pretrained(Word_Embedding_Matrix) # !
embedding.requires_grad = False # !!
# True : 학습하는 도중, NLI든 Sentiment Analysis든 Word Embeddding도 함께 학습됨 -> 속도 느려짐
# False : 학습하는 도중, Word Embedding 함께 학습되지 않음 -> 속도 빨라짐

In [45]:
torch.tensor(word2vec_model.key_to_index["최민식"])

tensor(3374)

In [46]:
Word_Embedding_Matrix[word2vec_model.key_to_index["최민식"]]

tensor([ 0.1661,  0.1376,  0.2718, -0.2589, -0.1917, -0.1670,  0.0786,  0.8293,
        -0.3246, -0.3827, -0.0050,  0.0569, -0.3408,  0.5075,  0.2207, -0.3238,
         0.0941,  0.1913, -0.4065, -0.3198, -0.3001,  0.0971,  0.5012,  0.2102,
         0.0762, -0.1125, -0.4830,  0.3280, -0.2707,  0.5109, -0.1236, -0.3021,
        -0.1867,  0.0347, -0.1057, -0.1898,  0.6698,  0.1175,  0.1084, -0.3507,
         0.5353, -0.1436,  0.0469,  0.2137,  0.2708, -0.1752,  0.2189, -0.3906,
         0.0615,  0.1847])

##### 6) 모델(Word_Embedding_Matrix) 결과 출력

(1) LookUp Tensor 추출

In [ ]:
idx = torch.tensor([[3374, 3500]]) # !!

(2) 모델(Word_Embedding_Matrix) 결과 출력

In [48]:
embedding(idx) # !

tensor([[[ 0.1661,  0.1376,  0.2718, -0.2589, -0.1917, -0.1670,  0.0786,
           0.8293, -0.3246, -0.3827, -0.0050,  0.0569, -0.3408,  0.5075,
           0.2207, -0.3238,  0.0941,  0.1913, -0.4065, -0.3198, -0.3001,
           0.0971,  0.5012,  0.2102,  0.0762, -0.1125, -0.4830,  0.3280,
          -0.2707,  0.5109, -0.1236, -0.3021, -0.1867,  0.0347, -0.1057,
          -0.1898,  0.6698,  0.1175,  0.1084, -0.3507,  0.5353, -0.1436,
           0.0469,  0.2137,  0.2708, -0.1752,  0.2189, -0.3906,  0.0615,
           0.1847],
         [-0.2130,  0.1342,  0.0240, -0.2017, -0.3097, -0.1833,  0.0236,
           0.7761,  0.0737, -0.5194,  0.0361, -0.2294, -0.0046,  0.1683,
           0.0983, -0.2456,  0.1758,  0.1167, -0.3551, -0.2649, -0.4216,
          -0.0147,  0.0832, -0.0218, -0.1615,  0.0104, -0.4859,  0.2571,
          -0.1444,  0.2602,  0.0054, -0.1433,  0.0316, -0.0458, -0.0478,
          -0.0378,  0.5086,  0.3014,  0.1019, -0.6047,  0.5557, -0.0207,
          -0.0767, -0.0719,  0.